###R W4
demo(graphics)
par(mfrow=c(1,1))

###
plot(x,y,...)
plot(y~x,...)
plot(M,...)
plot(list,...)

n=20
x=rnorm(n)
y=rnorm(n)
plot(x,y)
plot(y~x)

data=cbind(x=x,y=y) #matrix
plot(data)

lst=list(x=x,y=y) #list
plot(lst)

load(url("http://www.stats.gla.ac.uk/~levers/rp/w5.RData"))
head(health)
plot(LifeExpectancy~HealthExpenditure,data=health)

plot(LifeExpectancy~HealthExpenditure,data=health,col=1+unclass(Region))

model=lm(LifeExpectancy~log(HealthExpenditure),data=health)
plot(model)

### bar plot
height=1:5
names(height)=c("one","two","three","four","five")
barplot(height,col=rainbow(5))

#If we want to use the function barplot to chart frequencies of categorical 
#variables, we first need to tabulate these using the function table.
par(las=3,mar=c(12.1,4.1,4.1,2.1)) #increase space for label
barplot(table(health$Region))
title("number of countries")

par(las=3,mar=c(12.1,4.1,4.1,2.1))
#discretisation of expenditure
health=transform(health,DiscExp=cut(HealthExpenditure,
                                    breaks=c(0,75,250,1000,10000),
                                  labels=c("<75","75-250","250-1000",">1000")))
#plot the bar chart
barplot(table(health$DiscExp,health$Region),col=2:5)

###cex.main = size of the title
###cex.axis = size of the axis
###cex.lab = size of the labels
###mar = margins between your plot and the four sides of the graphical window. 
###The order is (bottom, left, top, right)
###las = orientation of the axis
par(cex.main = 0.5, cex.axis = 1, cex.lab = 0.01, mar = c(4,7,4,2), las = 3)

#add a legend
legend("top",fill=2:5,c("<75","75-200","250-1000",">1000"))

###Boxplot function
par(las=3,mar=c(12.1,4.1,4.1,2.1))
boxplot(health$HealthExpenditure~health$Region)

###histogram can be generated by using the function hist(x,)
hist(health$LifeExpectancy)

###use break=n, or break=vector 
hist(health$LifeExpectancy,breaks=3)

### a plot of density of health expenditure can be created using
plot(density(health$LifeExpectancy))

###The fourth to sixth column of the health expenditure
###data contain continuous data, which we
###can visualise using a scatterplot matrix.
pairs(health[,4:6],
      col=1+unclass(health$Region))
?pairs
###A matrix of scatterplots is produced.

###legend function
plot(LifeExpectancy~HealthExpenditure,data=health,col=1+unclass(Region))
legend("bottomright",pch=1,col=1+1:nlevels(health$Region),
       legend=levels(health$Region))
title("links btw health expen. and life expec.")

###The function lines and points can be used to 
#add lines or points to an existing plot. lines behaves like
#plot using type="l",", and points behaves like plot using type="p",

###Suppose we want to highlight the observations belonging 
#to the UK, the US and Australia in the
#plot of health expenditure and life expectancy.
health2=subset(health,Country=="Australia"|Country=="United Kingdom"
               |Country=="United States")
health2
plot(LifeExpectancy~HealthExpenditure,data=health,
     col=1+unclass(Region))
###and we can then draw the points for these three countries 
#with a filled circle ( pch=16) and twice the size ( cex=2):
points(health2$Heal,health2$Life,
       col=1+unclass(health2$Re),pch=16,cex=2)


#The abline function
#The function abline can be used to add a straight line to an existing plot:
#• abline(h=ypos, ...) draws a horizontal line at ypos.
#• abline(v=xpos, ...) draws a vertical line at xpos.
#• abline(a=intercept, b=slope, ...) draws a line with intercept as 
#its intercept and slope as its slope.
#col, lwd and lty can be used as additional arguments

### adding text
#The function text(x, y, text, ...) plots 
#the text text (one character string or a vector of strings)
plot(LifeExpectancy~HealthExpenditure,data=health,
     col=1+unclass(Region))
points(health2$Heal,health2$Life,
       col=1+unclass(health2$Re),pch=16,cex=2)
text(health2$HealthExpenditure,health2$LifeExpectancy,
     health2$Country,adj=c(1,1))

###Drawing rectangles and polygons
#The functions rect and polygon can be 
#used to draw filled rectangles and polygons

#rect(xleft, ybottom, xright, ytop, ...) draws a rectangle with bottom left corner (xleft, ybottom)
#and top right corner (xright, ytop).
#polygon(x, y, ...) draws a polygon with vertices in (x, y).
#The following optional arguments can be used:
#• border: the colour of the outline. Use border=NA to draw no outline.
#• lwd / lty: the line width / line type of the outline.
#• col: the colour used for filling the polygon. Use col=NA for a transparent rectangle / polygon (i.e. with

#Example 15 The following R code draws a red circle of radius 1 
#having a blue outline. Note the use of plot with argument 
#type=n to set up the plot (coordinate axes, etc.).
par(mfrow=c(1,1),pty="s")
?par
#pty:A character specifying the type of plot region to be used; "s" generates a square plotting region and "m" generates the maximal plotting region.
t=seq(0,2*pi,length.out=100)
circle=cbind(sin(t),cos(t))
plot(circle,type="n",xlab="x",ylab="y")
polygon(circle,col="red",border="blue",lwd=2)

###Mathematical notation in plots
#The text arguments used to display text in graphics (xlab, ylab,main, sub, . . . ) and the function text can
#be used as well to typeset mathematical formulae in a TeX-like manner. The formulae are not enclosed in
#quotation marks, but given as an argument to the functions quote or expression, as the following example shows:


theta <- seq(0, 1, by=0.01)
plot(theta, sqrt(theta)/pi, type="l",
     xlab=quote(theta), ylab=quote(sqrt(theta)/pi),
     main=quote("The function "*f(theta)==frac(sqrt(theta),pi)))
#The functions persp(x, y, M, ...), image(x, y, M, ...), contour(x, y, M, ...), and filled.contour(x,
#y, M, ...) can be used to visualise functions f(x, y) of two variable x and y. The functions are also useful
#when visualising spatial or map data.
x=seq(-2,2,len=50)
y=seq(-2,2,len=50)
z=matrix(nrow=length(x),ncol=length(y))
for(i in 1:length(x))
  for(j in 1:length(y))
    z[i,j]=dnorm(x[i])*dnorm(y[j])
z
contour(x,y,z)
?dnorm
image(x,y,z,col=rainbow(100))
?image

persp(x,y,z,theta=30,phi=30,col="yellow",shade=0.5)
?persp
#The arguments theta and phi of persp allow for changing the angle from which the surface is viewed

#Margins
#The margins of the plot can be changed by calling 
#par(mar=c(bottom, left, top, right)) before plotting.

#par(mfrow=c(nrows, ncols)) divides the figure into nrows rows and ncols columns, which will be used in
#row-wise order, as shown in Figure 1.
#par(mfcol=c(nrows, ncols)) divides the figure into nrows rows and ncols columns, which will be used in
#column-wise order, as shown in Figure 2.
layout.matrix=rbind(c(1,1,2),c(1,1,3))
layout(layout.matrix)

plot(LifeExpectancy~HealthExpenditure, data=health, col=1+unclass(Region),
     cex=sqrt(Population)/mean(sqrt(Population)), pch=16)
title("Link between health expenditure and life expectancy")

setwd("/Users/kurisuuu/Documents/glasgow_stats_2021/introtoR/W4data")
hp <- read.csv("hp.csv") 
head(hp)
plot(NULL, xlim=range(hp$Year), ylim=range(hp[,-1]),
     xlab="Year", ylab="Median house price")
for (i in 2:ncol(hp)) {lines(hp$Year, hp[,i], col=i)}
legend("topleft", lty=1, col=2:ncol(hp), colnames(hp)[-1],cex=0.5)

###or

matplot(hp$Year, hp[,-1], type="l", col=2:ncol(hp), lty=1,
        xlab="Year", ylab="Median house price")
legend("topleft", lty=1, col=2:ncol(hp), colnames(hp)[-1],cex=0.5)

View(hp)
?matplot
hp[,-1]
#-1 means does not include the first column!!!